name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2   # Upgrade to v2 to avoid warnings
        with:
          username: ${{ secrets.DOCKERHUB_USER }}   # Ensure this secret is correct
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Ensure this secret is correct
          
      - name: Checkout code
        uses: actions/checkout@v2      # Correct action name
      
      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"  # Ensure Docker is set up properly

      - name: Run Linter
        run: docker compose run --rm app sh -c "flake8"   # Ensure flake8 is installed in Docker container
